name: Linting
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs: 
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Solhint
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm install -g solhint
      - run: make solhint

